class_name Beatmap
extends RefCounted
# Stub — port of main.py beats_from_media / detect_beats_madmom.
# The Pyglet build shells out to ffmpeg + madmom RNNOnsetProcessor (main.py:284).
# In Godot, keep the same cache contract (songs/.cache/<stem>_<md5>_<diff>.json)
# so you can reuse existing .cache files generated by the Python build.

# To get real audio analysis without a Python sidecar:
#  Option A: ship a small Python helper (rhythmgame/main.py --export-cache <file>)
#  Option B: use Godot's AudioStream + Aubio GDExtension for onset detection later.

const CACHE_VERSION := 4
const HISTORY_MAX := 10

static func _md5_variants(path: String) -> Array:
	# Python uses Path.resolve() with backslashes; Godot's path may be forward slashes.
	# Try both so cache lookup works regardless.
	var a := path.md5_text().substr(0, 8)
	var b := path.replace("/", "\\").md5_text().substr(0, 8)
	var c := path.replace("\\", "/").md5_text().substr(0, 8)
	# also try globalized res://
	var gpath := path
	if path.begins_with("res://"):
		gpath = ProjectSettings.globalize_path(path)
		if not gpath.is_empty():
			var d := gpath.md5_text().substr(0, 8)
			var e := gpath.replace("/", "\\").md5_text().substr(0, 8)
			return [a, b, c, d, e]
	return [a, b, c]

static func _find_cache_file(media_path: String, difficulty: String) -> String:
	var stem := media_path.get_file().get_basename()
	var diff := difficulty.to_lower()
	var candidates: Array[String] = []
	for h: String in _md5_variants(media_path):
		candidates.append("user://cache/%s_%s_%s.json" % [stem, h, diff])
		candidates.append("C:/Users/LOK0008/rhythmgame/songs/.cache/%s_%s_%s.json" % [stem, h, diff])
	# also try res://songs/.cache
	for h: String in _md5_variants(media_path):
		candidates.append("res://songs/.cache/%s_%s_%s.json" % [stem, h, diff])
	for cp: String in candidates:
		if FileAccess.file_exists(cp):
			return cp
	# fallback: glob scan by stem (ignores md5) — handles any slash mismatch or moved file
	for base: String in ["user://cache", "C:/Users/LOK0008/rhythmgame/songs/.cache", "res://songs/.cache"]:
		var dir := DirAccess.open(base)
		if dir == null: continue
		dir.list_dir_begin()
		var f: String = dir.get_next()
		while f != "":
			if not dir.current_is_dir() and f.begins_with(stem + "_") and f.ends_with("_%s.json" % diff):
				var cand: String = base.path_join(f)
				if FileAccess.file_exists(cand):
					return cand
			f = dir.get_next()
	return ""

static func cache_path(media_path: String, difficulty: String) -> String:
	# primary write path — use backslash-variant to match Python's resolve() md5
	var stem := media_path.get_file().get_basename()
	var h := media_path.replace("/", "\\").md5_text().substr(0, 8)
	return "user://cache/%s_%s_%s.json" % [stem, h, difficulty.to_lower()]

static func legacy_cache_path(media_path: String, difficulty: String) -> String:
	var stem := media_path.get_file().get_basename()
	var h := media_path.replace("/", "\\").md5_text().substr(0, 8)
	return "C:/Users/LOK0008/rhythmgame/songs/.cache/%s_%s_%s.json" % [stem, h, difficulty.to_lower()]

static func load_cached(media_path: String, difficulty: String) -> Variant:
	var cp := _find_cache_file(media_path, difficulty)
	if cp.is_empty():
		return null
	var f := FileAccess.open(cp, FileAccess.READ)
	if not f: return null
	var data = JSON.parse_string(f.get_as_text())
	if data == null or not data.has("beatmap"): return null
	return data

static func ensure_beatmap(media_path: String, difficulty: String) -> Variant:
	# Try cache first, then generate via actual Python algorithm (main.py beats_from_media)
	var cached = load_cached(media_path, difficulty)
	if cached != null:
		return cached
	# Try to generate via Python helper (uses madmom/librosa, same as Pyglet)
	var py_candidates: Array[String] = [
		"C:/Users/LOK0008/AppData/Local/Python/pythoncore-3.14-64/python.exe",
		"C:/Users/LOK0008/AppData/Local/Python/bin/python.exe",
		"python",
		"py"
	]
	var helper := "C:/Users/LOK0008/rhythmgame/generate_beatmap.py"
	if not FileAccess.file_exists(helper):
		# also try res://
		helper = ProjectSettings.globalize_path("res://generate_beatmap.py")
		if not FileAccess.file_exists(helper):
			return null
	for py in py_candidates:
		var args: Array[String] = [helper, media_path, difficulty]
		var out: Array = []
		var exit_code := OS.execute(py, args, out, true)
		if exit_code == 0:
			var cached2 = load_cached(media_path, difficulty)
			if cached2 != null:
				print("[Beatmap] generated via Python: %s [%s]" % [media_path.get_file(), difficulty])
				return cached2
		else:
			print("[Beatmap] Python generate failed (%s): %s" % [py, " ".join(out)])
	# Fallback: try GDScript generator if Python not available (dynamic load to avoid circular parse)
	var BeatmapGeneratorScript = load("res://scripts/BeatmapGenerator.gd")
	if BeatmapGeneratorScript != null:
		var gd_gen = BeatmapGeneratorScript.new()
		var fallback = gd_gen.generate_from_media(media_path, difficulty)
		if fallback != null:
			return fallback
	return null

# --- Per-song history — mirrors main.py:305 history helpers ---
static func load_history(media_path: String, difficulty: String) -> Array:
	var cp := _find_cache_file(media_path, difficulty)
	if cp.is_empty():
		return []
	var f := FileAccess.open(cp, FileAccess.READ)
	if not f: return []
	var data = JSON.parse_string(f.get_as_text())
	if data == null or not data.has("history") or not data["history"] is Array:
		return []
	return data["history"]

static func add_history_entry(media_path: String, difficulty: String, entry: Dictionary) -> void:
	var cp := cache_path(media_path, difficulty)
	var legacy := legacy_cache_path(media_path, difficulty)
	var data: Dictionary = {}
	if FileAccess.file_exists(cp):
		var f := FileAccess.open(cp, FileAccess.READ)
		if f:
			var txt := f.get_as_text()
			var parsed = JSON.parse_string(txt)
			if parsed is Dictionary: data = parsed
	elif FileAccess.file_exists(legacy):
		var lf := FileAccess.open(legacy, FileAccess.READ)
		if lf:
			var txt2 := lf.get_as_text()
			var parsed2 = JSON.parse_string(txt2)
			if parsed2 is Dictionary: data = parsed2
	if not data.has("history") or not data["history"] is Array:
		data["history"] = []
	data["history"].append(entry)
	while data["history"].size() > HISTORY_MAX:
		data["history"].remove_at(0)
	DirAccess.make_dir_recursive_absolute("user://cache")
	var out := FileAccess.open(cp, FileAccess.WRITE)
	if out: out.store_string(JSON.stringify(data, "\t"))

static func best_grade_from_history(hist: Array) -> String:
	var order := {"S": 5, "A": 4, "B": 3, "C": 2, "D": 1}
	var best := ""; var best_v := 0
	for e in hist:
		var g: String = str(e.get("grade", "")).strip_edges().to_upper()
		if g.length() > 0: g = g.substr(g.length()-1, 1)
		if not order.has(g): g = "D"
		var v: int = order[g]
		if v > best_v:
			best_v = v; best = g
	return best

static func best_max_fc_from_history(hist: Array) -> int:
	var best := 0
	for e in hist: best = maxi(best, int(e.get("max_fc", 0)))
	return best

static func best_score_from_history(hist: Array) -> int:
	var best := 0
	for e in hist: best = maxi(best, int(e.get("score", 0)))
	return best

static func density_to_rating(nps: float) -> int:
	# mirrors main.py:106 density_to_rating
	var clamped := clampf((nps - 1.45) / (3.0 - 1.45), 0.0, 1.0)
	return int(lerpf(1, 20, clamped))

static func generate_demo_pattern(bpm: float = 128.0, bars: int = 16) -> Array:
	var interval := 60.0 / bpm
	var beats: Array = []
	var lanes := ["d","f","j","k"]
	for i in range(int(bars * 4 * 60.0 / bpm / interval)):
		beats.append([i * interval, lanes[i % 4]])
	return beats
